DECLARE
  c INT;
BEGIN
  SELECT COUNT(*)
  INTO c
  FROM user_tables
  WHERE table_name = 'GT_TABLENAME_A';
  IF c             = 1 THEN
    EXECUTE immediate 'DROP TABLE GT_TABLENAME_A';
    EXECUTE immediate 'CREATE GLOBAL TEMPORARY TABLE GT_TABLENAME_A  
    (     
      FIELD_A VARCHAR2(10 BYTE), 
      FIELD_B VARCHAR2(10 BYTE) 
	) ON COMMIT PRESERVE ROWS' ;
  ELSE
    EXECUTE immediate 'CREATE GLOBAL TEMPORARY TABLE GT_TABLENAME_A  
    (     
      FIELD_A VARCHAR2(10 BYTE), 
      FIELD_B VARCHAR2(10 BYTE) 
	) ON COMMIT PRESERVE ROWS' ;
  END IF;
END;
